version: '3.4'

services:
  factorysimulation:
    image: bpafactoryintegrationandsimulation
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ../aws-certs:/app/aws-certs # aws-certs should lay one directory above
